name: postgres_dart
description: Wraps postgres package with dart methods for performing sql queries.
version: 1.0.0
repository: https://github.com/EddieKamau/postgres_dart

environment:
  sdk: '>=2.19.0 <4.0.0'


dependencies:
  postgres: ^2.5.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
