name: postgres_dart
description: Wraps postgres package with dart methods for performing sql queries.
version: 1.0.0
repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-171.0.dev <4.0.0'


dependencies:
  postgres: ^2.5.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
