name: postgres_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-171.0.dev <4.0.0'

# Add regular dependencies here.
dependencies:
  postgres: ^2.5.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
